// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'progress-btn-mark-all'
  | 'progress-btn-refresh'
  | 'progress-no-toc'
  | 'progress-section-head'
  | 'progress-section-sidenav'
  | 'startup-begin'
  | 'startup-finish';
